### ISSUE TITLE
incompatible with ansible-galaxy install

### ISSUE THREAD

**Issue by aioue** [dataloop/dataloop-ansible#11]
The directory structure of this repo is more like a full ansible tree rather than a a role, meaning that you cannot simply use this repo as part of an existing ansible tree by typing `ansible-galaxy install https://github.com/dataloop/dataloop-ansible/tree/master/roles/dataloop-agent`.

By just having the directories listed under `roles/dataloop-agent` and moving the vars to a defaults file inside that, you'd have a role that can be managed and updated on customer boxes using the inbuilt `ansible-galaxy` command.

**Comment by sacreman** [comment]
Hi @aioue we'll get this fixed up. @tomashley gets a bit protective over his config repos so I'll probably wait until he comes back from holiday next week before attempting to change it :)

**Comment by aioue** [comment]
@sacreman I do too :)

Have drafted up a quick example based on your code, feel free to crib from it if it's helpful.

https://github.com/aioue/ansible-role-dataloop_example

**Comment by tomashley** [comment]
https://github.com/dataloop/dataloop-ansible/commit/ad3eac2d42c271780b4ded4ca410c3250ea2bfee converted

Vagrantfile tests passed
